### ISSUE TITLE
Latest Chrome update Version 114.0.5735.106 causes rendering problems

### ISSUE THREAD

**Issue by ChazHollywood** [gkjohnson/three-gpu-pathtracer#441] opened 2023-06-08 19:28 UTC
Everything was working fine for me yesterday prior to the latest Chrome update. 

See screenshot from live demo pages:

<img width="531" alt="Screenshot 2023-06-08 at 12 25 05 PM" src="https://github.com/gkjohnson/three-gpu-pathtracer/assets/135338745/ae267554-c114-4d50-9abd-7a42c80d351b">

 - Device: Desktop
 - OS: MacOS
 - GPU: Apple M1 Pro
 - Browser: Chrome

**Comment by PalashGarg19** [comment] 2023-06-23 03:54
Facing the same issue.
I am using Linux(Ubuntu 22.04), but this issue is occuring on Chrome browser only, on firefox it is working fine.

**Comment by gkjohnson** [comment] 2023-06-28 03:42
This is a browser regression. I recommend submitting a chrome issue so the team can know about it but generally I can no longer chase moving targets and try to accomodate the quirks that are added and removed different devices and platforms.

When I have time I will be looking into moving this project to use compute shaders and WebGPU assuming it's more stable than the current middleware transformations browsers are working on now.

To be clear - I mean no shade to Chrome and browser teams. Normalizing all device and driver behavior to operate consistently in WebGL is a massive undertaking. But when a project like this is so sensitive to even minor shader compilation and precision changes it's not tenable to keep adjusting the project.

**Comment by ChazHollywood** [comment] 2023-07-09 23:43
@gkjohnson 
I’ve been using your software in the development of a photography lighting visualizer, which works in conjunction with some hardware we are developing. 

The pathtracer works great for this application and I’d love to see it developed further. I understand the frustration with unpredictable browser updates breaking things, but I’d love to encourage you to press on with this project.

I’d be open to sponsoring the project or putting a bounty on fixing this plus the Safari comparability issues. I see you’ve got a lot of things you are working on, but wanted to reach out to see what you think it would take to get this back up and running. Please let me know what you think.

Thank you!

**Comment by mattni** [comment] 2023-08-23 08:39
Hi! This seems to be only Chrome issue. I have same issue when using Chrome with OPENGL backend for angle (D3D11 works well). Firefox and Edge works well with OPENGL backend too.

I investigate issue and found something. Maybe this should be in Three-mesh-bvh repo because problem is there.
The same issue occours with simple normal PT example: https://gkjohnson.github.io/three-mesh-bvh/example/bundle/gpuPathTracingSimple.html
![image](https://github.com/gkjohnson/three-gpu-pathtracer/assets/29143059/680b002c-e042-49e0-a6a2-67b52486610f)
(BG-color is changed to orange to clarify issue)

Issue found from bool bvhIntersectFirstHit() function. It returns correctly true, when intersected. 
The problem is that output variables are updated even when intersectTriangles() function result is false. Issue dissappears when output variables are updated only when intersectTriangles returns true.

https://github.com/gkjohnson/three-mesh-bvh/blob/d1b731eb3f3403432ab44926f3996b81c645ebdd/src/gpu/shaderFunctions.js#L245

Workaround example:
![image](https://github.com/gkjohnson/three-gpu-pathtracer/assets/29143059/69356862-1cb8-4520-8d01-b1075c83fccc)

The same page renders correctly using previous workaround.
![image](https://github.com/gkjohnson/three-gpu-pathtracer/assets/29143059/dc7b5b1e-1c5b-4039-9149-c8de0a387453)

I didn't test but maybe same issue founds in bvhClosestPointToPoint() function, because function structure looks similar.

Device: 
Device: Desktop
OS: Windows 11
GPU: RTX 3070 Ti
Browser: Chrome 116.0.5845.111

**Comment by gkjohnson** [comment] 2023-08-24 01:58
@mattni Great! Thank you so much for looking into this. Do you mind making a PR into three-mesh-bvh and we can talk about the specifics of the change in more detail? Then we can get a new version of what we need to released.

**Comment by mattni** [comment] 2023-08-24 18:42
Sure! I will do it (hopefully tomorrow).  Thank you for the great libraries!

**Comment by gkjohnson** [comment] 2023-09-03 13:52
Hi @mattni! Just a friendly ping on this - again I appreciate the help!

**Comment by mattni** [comment] 2023-09-03 14:19
Hi @gkjohnson! Sorry, it has been so busy times. I'm able to do it within a few days.

**Comment by gkjohnson** [comment] 2023-09-08 07:21
With the latest published version of three-mesh-bvh this should be addressed - thanks @mattni!

If there's still an issue we can reopen.

**Closed by gkjohnson** 2023-09-08 07:21 UTC
Labels: browser / device issue
