### ISSUE TITLE
@types/three-gpu-pathtracer

### ISSUE THREAD

**Issue by JerryI** [gkjohnson/three-gpu-pathtracer#430] opened 2023-04-06 15:43 UTC
> Could not find a declaration file for module 'three-gpu-pathtracer/build/index.module'.

Create `@types/three-gpu-pathtracer` package contains a declaration for the module

**Comment by gkjohnson** [comment] 2023-04-07 07:06
Duplicate of #18

**Comment by gkjohnson** [comment] 2023-04-07 07:07
Feel free to make a PR if you'd like to add type definitions!

**Closed by gkjohnson** 2023-04-07 07:06 UTC
Labels: duplicate, enhancement
